"use client";

import { useState } from "react";
import { Braces, Check, Code2, Database, Lightbulb, RefreshCcw, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const codeExamples = [
  ["Primitive values", `const name = "Muhammad Zubair";\nconst age = 30;\nconst isDeveloper = true;\n\nlet email;\nconst middleName = null;`],
  ["Objects and collections", `const user = { name: "Zubair", age: 30 };\nconst products = ["Laptop", "Phone"];\nconst today = new Date();\nconst tags = new Set(["aws", "javascript"]);`],
  ["Primitive copy", `let a = 10;\nlet b = a;\nb = 20;\n\nconsole.log(a); // 10\nconsole.log(b); // 20`],
  ["Reference sharing", `const user1 = { name: "Zubair" };\nconst user2 = user1;\nuser2.name = "Ali";\n\nconsole.log(user1.name); // Ali`],
];

const quizQuestions = [
  { question: "How many primitive data types does JavaScript have?", options: ["5", "6", "7", "8"], answer: 2, explanation: "JavaScript has seven primitive types: string, number, bigint, boolean, undefined, null, and symbol." },
  { question: "Which value represents an intentional empty value?", options: ["undefined", "null", "false", "0"], answer: 1, explanation: "null is explicitly assigned to represent no value. undefined usually means a declared value has not been assigned." },
  { question: "What does typeof null return?", options: ["null", "undefined", "object", "empty"], answer: 2, explanation: "typeof null returns object because of a historical JavaScript behavior that cannot be changed without breaking existing code." },
  { question: "Which type is best for integers beyond Number.MAX_SAFE_INTEGER?", options: ["Number", "BigInt", "Symbol", "Object"], answer: 1, explanation: "BigInt represents arbitrarily large integers, such as 9007199254740993n." },
  { question: "What does typeof [] return?", options: ["array", "list", "object", "collection"], answer: 2, explanation: "Arrays are objects in JavaScript. Use Array.isArray(value) when you specifically need to detect an array." },
  { question: "How are primitive values copied?", options: ["By reference", "By value", "By pointer only", "They cannot be copied"], answer: 1, explanation: "Assigning a primitive creates an independent value, so changing the copy does not change the original." },
  { question: "Which type creates unique identifiers?", options: ["Symbol", "BigInt", "Boolean", "Function"], answer: 0, explanation: "Symbol creates unique primitive values that are useful for collision-resistant property keys." },
  { question: "Which statement best describes a reference type?", options: ["It can only store text", "It is always immutable", "Variables can share the same object", "It cannot be assigned"], answer: 2, explanation: "Objects, arrays, and functions are reference values. Two variables can refer to the same object in memory." },
  { question: "What is the best way to check whether a value is an array?", options: ["typeof value === \"array\"", "value.isArray()", "Array.isArray(value)", "value instanceof List"], answer: 2, explanation: "typeof arrays returns object, so Array.isArray(value) is the reliable built-in check." },
  { question: "Which example shows an unassigned variable?", options: ["const x = null", "let x;", "const x = false", "const x = 0"], answer: 1, explanation: "let x declares a variable without assigning a value, so reading x returns undefined." },
];

function CodeBlock({ title, code }: { title: string; code: string }) {
  return <Card className="border-white/10 bg-card/60"><CardHeader><CardTitle className="text-lg">{title}</CardTitle></CardHeader><CardContent><pre className="overflow-auto rounded-lg border border-white/10 bg-background/80 p-4 font-code text-xs leading-6 text-muted-foreground"><code>{code}</code></pre></CardContent></Card>;
}

function Quiz() {
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const correct = quizQuestions.reduce((score, question, index) => score + (answers[index] === question.answer ? 1 : 0), 0);
  return <section className="space-y-5"><div><Badge variant="outline" className="border-primary/20 bg-primary/5 text-primary">Practice quiz</Badge><h2 className="mt-3 font-headline text-3xl font-bold">JavaScript Data Types Quiz</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">Choose an answer to see the explanation and check your understanding.</p></div>{quizQuestions.map((question, index) => <Card key={question.question} className="border-white/10 bg-card/70"><CardContent className="space-y-4 p-5"><p className="font-semibold leading-6">{index + 1}. {question.question}</p><div className="grid gap-2">{question.options.map((option, optionIndex) => { const selected = answers[index] === optionIndex; const isCorrect = optionIndex === question.answer; return <button key={option} type="button" onClick={() => setAnswers((current) => ({ ...current, [index]: optionIndex }))} className={`rounded-lg border p-3 text-left text-sm transition-colors ${selected ? (isCorrect ? "border-success/50 bg-success/10" : "border-destructive/50 bg-destructive/10") : "border-white/10 bg-background/30 hover:border-primary/30"}`}><span className="mr-2 font-semibold">{String.fromCharCode(65 + optionIndex)}.</span>{option}{selected ? <span className="mt-2 block border-t border-white/10 pt-2 text-xs leading-5 text-muted-foreground">{question.explanation}</span> : null}</button>; })}</div></CardContent></Card>)}<Card className="border-primary/20 bg-primary/5"><CardContent className="flex flex-col gap-3 p-5 md:flex-row md:items-center md:justify-between"><p className="font-semibold">Score: {correct} / {quizQuestions.length}</p><Button variant="outline" className="rounded-full border-white/10" onClick={() => setAnswers({})}><RefreshCcw className="mr-2 h-4 w-4" />Reset Quiz</Button></CardContent></Card></section>;
}

export function JavaScriptDataTypesLesson() {
  return <div className="relative overflow-hidden"><div className="absolute inset-0 hero-gradient -z-10" /><section className="container mx-auto px-4 pb-16 pt-28"><div className="mx-auto max-w-4xl text-center"><Badge variant="outline" className="mb-5 rounded-full border-primary/20 bg-primary/5 px-4 py-1 text-primary"><Code2 className="mr-2 h-3.5 w-3.5" />JavaScript Fundamentals</Badge><h1 className="text-5xl font-headline leading-tight lg:text-7xl"><span className="gradient-text">JavaScript Data Types</span></h1><p className="mx-auto mt-6 max-w-3xl text-xl leading-relaxed text-muted-foreground">Understand the values JavaScript can store, how primitives differ from objects, and how data moves through memory.</p><p className="mx-auto mt-5 max-w-3xl text-base leading-8 text-muted-foreground">Learn typeof, null versus undefined, BigInt, Symbol, arrays, reference sharing, common interview questions, and practical coding patterns.</p></div></section>
    <section className="container mx-auto space-y-10 px-4 pb-24"><Card className="border-primary/20 bg-card/60 backdrop-blur-xl"><CardContent className="space-y-4 p-6"><div className="flex items-center gap-2 text-primary"><Braces className="h-5 w-5" /><h2 className="font-headline text-2xl font-bold">What Are Data Types?</h2></div><p className="text-sm leading-7 text-muted-foreground">A data type defines the kind of value a variable can hold and the operations that can be performed on it. An e-commerce product uses several types at once: a name is a string, a price is a number, inventory status is a boolean, and the product itself is an object.</p><div className="grid gap-3 md:grid-cols-2">{[["Product name", '"iPhone 16"', "String"], ["Price", "999.99", "Number"], ["In stock", "true", "Boolean"], ["Product", "{ name, price }", "Object"]].map(([label, value, type]) => <div key={label} className="rounded-lg border border-white/10 bg-background/40 p-4"><p className="text-xs uppercase tracking-widest text-muted-foreground">{label}</p><p className="mt-2 font-code text-sm text-primary">{value}</p><p className="mt-1 text-sm text-muted-foreground">{type}</p></div>)}</div></CardContent></Card>
      <Card className="border-white/10 bg-card/70"><CardHeader><CardTitle className="font-headline text-2xl">JavaScript Data Type Map</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-5 md:grid-cols-2"><div className="rounded-xl border border-primary/20 bg-primary/5 p-5"><h3 className="font-semibold text-primary">Primitive (7)</h3><div className="mt-3 flex flex-wrap gap-2">{["String", "Number", "BigInt", "Boolean", "Undefined", "Null", "Symbol"].map((item) => <Badge key={item} variant="secondary">{item}</Badge>)}</div><p className="mt-4 text-sm leading-6 text-muted-foreground">Primitives are immutable values copied independently by value.</p></div><div className="rounded-xl border border-white/10 bg-background/40 p-5"><h3 className="font-semibold">Reference: Object</h3><div className="mt-3 flex flex-wrap gap-2">{["Array", "Function", "Date", "Map", "Set", "Custom object"].map((item) => <Badge key={item} variant="outline">{item}</Badge>)}</div><p className="mt-4 text-sm leading-6 text-muted-foreground">Objects are collections whose references can be shared between variables.</p></div></div></CardContent></Card>
      <div className="grid gap-6 lg:grid-cols-2">{codeExamples.map(([title, code]) => <CodeBlock key={title} title={title} code={code} />)}</div>
      <Card className="border-primary/20 bg-primary/5"><CardContent className="space-y-4 p-6"><div className="flex items-center gap-2 text-primary"><Database className="h-5 w-5" /><h2 className="font-headline text-2xl font-bold">Memory and typeof</h2></div><p className="text-sm leading-7 text-muted-foreground">Primitive assignments create independent values. Object assignments copy a reference to the same heap object, so changing one reference can be visible through another.</p><div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border border-white/10 bg-background/50 p-4 font-code text-xs leading-6 text-muted-foreground">Stack: a → 10<br />Stack: b → 10<br /><br />Independent primitive values</div><div className="rounded-lg border border-white/10 bg-background/50 p-4 font-code text-xs leading-6 text-muted-foreground">Stack: user1 ─┐<br />Stack: user2 ─┘<br />Heap: {'{ name: "Zubair" }'}<br /><br />Shared object reference</div></div><div className="grid gap-3 md:grid-cols-3">{[["typeof \"Hello\"", "string"], ["typeof 10", "number"], ["typeof []", "object"], ["typeof function() {}", "function"], ["typeof undefined", "undefined"], ["typeof null", "object"]].map(([expression, result]) => <div key={expression} className="rounded-lg border border-white/10 bg-background/40 p-3 font-code text-xs"><p>{expression}</p><p className="mt-1 text-primary">→ {result}</p></div>)}</div></CardContent></Card>
      <Card className="border-success/20 bg-success/10"><CardContent className="space-y-4 p-6"><div className="flex items-center gap-2 text-success"><ShieldCheck className="h-5 w-5" /><h2 className="font-headline text-2xl font-bold">Interview Questions and Best Practices</h2></div><div className="grid gap-3 md:grid-cols-2">{["Why is typeof null object? It is a historical compatibility quirk.", "Why is an array an object? Arrays inherit object behavior and typeof reports object.", "Use Array.isArray(value) to detect arrays.", "Use null intentionally; use undefined for an unassigned value.", "Use BigInt for integers beyond Number's safe range.", "Avoid comparing objects directly: {} === {} is false because references differ.", "Use strict equality and avoid implicit type coercion.", "Remember: primitives are copied by value; objects share references."].map((item) => <div key={item} className="flex gap-2 rounded-lg border border-white/10 bg-background/40 p-4 text-sm leading-6 text-muted-foreground"><Check className="mt-1 h-4 w-4 shrink-0 text-success" />{item}</div>)}</div></CardContent></Card>
      <Quiz />
    </section></div>;
}
